# Generated by Django 3.0.6 on 2020-06-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
