# Generated by Django 3.0.6 on 2020-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200610_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=100000000)),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='bestoffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image1', models.ImageField(upload_to='bestoffers')),
                ('image2', models.ImageField(upload_to='bestoffers')),
                ('image3', models.ImageField(upload_to='bestoffers')),
            ],
            options={
                'verbose_name': 'bestoffer',
                'verbose_name_plural': 'bestoffers',
                'ordering': ('name',),
            },
        ),
    ]
