# Generated by Django 3.0.6 on 2020-06-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_ad_bestoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='image', upload_to='ads'),
        ),
    ]
