# Generated by Django 3.0.6 on 2020-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200613_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestoffer',
            name='url1',
            field=models.CharField(default='url', max_length=1000000),
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='url2',
            field=models.CharField(default='url', max_length=1000000),
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='url3',
            field=models.CharField(default='url', max_length=1000000),
        ),
    ]
