# Generated by Django 3.0.6 on 2020-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200613_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffer',
            name='url1',
            field=models.CharField(blank=True, default='url', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='bestoffer',
            name='url2',
            field=models.CharField(blank=True, default='url', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='bestoffer',
            name='url3',
            field=models.CharField(blank=True, default='url', max_length=1000000),
        ),
    ]
