# Generated by Django 3.0.6 on 2020-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200622_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestoffer',
            name='image',
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='image1',
            field=models.ImageField(blank=True, default='image1', upload_to='bestoffers'),
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='image2',
            field=models.ImageField(blank=True, default='image2', upload_to='bestoffers'),
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='image3',
            field=models.ImageField(blank=True, default='image3', upload_to='bestoffers'),
        ),
    ]
