# Generated by Django 3.0.6 on 2020-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200622_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
